name: Deploy
on:
  push:
    tags:
      - v*
concurrency:
  group: deploy-github-pages
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - id: setup-nodejs
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - id: install
        name: Install
        run: npm install
      - id: build
        name: Build
        run: npm run build
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-pages@v1
        with:
          path: ./app/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}}
    steps:
      - id: deploy
        name: Deploy
        uses: actions/deploy-pages@v1
